# Generated by Django 4.1 on 2022-08-20 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_first_installment_course_second_installment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='description',
            field=models.TextField(default='This is a basic course'),
            preserve_default=False,
        ),
    ]
