# Generated by Django 4.1 on 2022-08-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_alter_course_duration_alter_course_first_installment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='first_installment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='second_installment',
        ),
        migrations.RemoveField(
            model_name='course',
            name='third_installment',
        ),
        migrations.CreateModel(
            name='CourseInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_installment', models.IntegerField()),
                ('second_installment', models.IntegerField()),
                ('third_installment', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
